name: Build, Test, and Deploy of 3-Tier-Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ECR_FRONTEND: ${{ secrets.AWS_ECR }}
  FRONTEND_DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  AWS_ECR_USERNAME: ${{ secrets.AWS_ECR_USERNAME }}
  AWS_ECR_BACKEND: ${{ secrets.AWS_ECR_BACKEND }}
  BACKEND_DOCKER_IMAGE: ${{ secrets.BACKEND_DOCKER_IMAGE }}
  AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
  AWS_EKS_CLUSTER_NAMESPACE: ${{ secrets.AWS_EKS_CLUSTER_NAMESPACE }}
  AWS_EKS_CLUSTER_REGION: ${{ secrets.AWS_EKS_CLUSTER_REGION }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

      # Configure AWS
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

      # ECR Login
    - name: Login to Amazon ECR
      run: |
        aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username ${{ env.AWS_ECR_USERNAME }} --password-stdin ${{ env.AWS_ECR_FRONTEND }}
        aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username ${{ env.AWS_ECR_USERNAME }} --password-stdin ${{ env.AWS_ECR_BACKEND }}

      # Building and Tagging Docker Image  
    - name: Build and Tag Docker Image
      run: |
        docker build -t ${{ env.FRONTEND_DOCKER_IMAGE }} ./frontend/.
        docker tag ${{ env.FRONTEND_DOCKER_IMAGE }}:latest ${{ env.AWS_ECR_FRONTEND }}/${{ env.FRONTEND_DOCKER_IMAGE }}:latest

        docker build -t ${{ env.BACKEND_DOCKER_IMAGE }} ./backend/.
        docker tag ${{ env.BACKEND_DOCKER_IMAGE }}:latest ${{ env.AWS_ECR_BACKEND }}/${{ env.BACKEND_DOCKER_IMAGE }}:latest

      # Pushing Docker Image to ECR
    - name: Push Docker Image to ECR
      run:  |
        docker push ${{ env.AWS_ECR_FRONTEND }}/${{ env.FRONTEND_DOCKER_IMAGE }}:latest
        docker push ${{ env.AWS_ECR_BACKEND }}/${{ env.BACKEND_DOCKER_IMAGE }}:latest

      # Updating kubeconfig
    - name: update kubeconfig
      run: aws eks update-kubeconfig --region ${{ env.AWS_EKS_CLUSTER_REGION }} --name ${{ env.AWS_EKS_CLUSTER_NAME }}

      # Deploying Configs to EKS
    - name: applying k8s configs
      run: |
        kubectl create namespace ${{ env.AWS_EKS_CLUSTER_NAMESPACE }} || true
        kubectl apply -f k8s_manifests/ 

      # Installing and Deploying Load Balancer 
    - name: Installing ALB
      run: |
        ./alb_install.sh
        kubectl apply -f k8s_manifests/alb_config/full_stack_lb.yaml
